export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_DETAIL_REQUEST = "POST_DETAIL_REQUEST";
export const POST_DETAIL_SUCCESS = "POST_DETAIL_SUCCESS";
export const POST_DETAIL_FAIL = "POST_DETAIL_FAIL";

export const POST_EDIT_REQUEST = "POST_EDIT_REQUEST";
export const POST_EDIT_SUCCESS = "POST_EDIT_SUCCESS";
export const POST_EDIT_FAIL = "POST_EDIT_FAIL";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";
